# «Обработка исключений и замыкания»  

## Кейс 1: Форматтер чисел
Ошибки случаются, и нужно уметь с ними работать. Мои коллеги разработали форму, которая принимает от пользователя количество покупаемых единиц товара. Меня попросили написать функцию-преобразователь, которая:
* возвращает число, если всё корректно;
* генерирует ошибку, если ввод не является числом в десятичной системе счисления.

### Процесс реализации
1. Написал функцию `parseCount` .
    * Аргументом функции было значение, которое необходимо распарсить.
    * Для парсинга использовал функцию `Number.parseFloat`.
    * Если результат парсинга — значение `NaN`, то появляется исключение с ошибкой *«Невалидное значение»*.
    * Вернул результат парсинга из функции.
2. Написал функцию `validateCount`.
    * Аргументом функции было значение, которое необходимо распарсить.
    * Попробовал распарсить значение с помощью функции `parseCount`.
    * Если распарсить удаётся успешно, то возвращаю результат.
    * Перехватил исключение, которое может выбрасывать функция `parseCount`.
    * Воернул ошибку из функции в случае перехвата исключения.

## Кейс 2: Треугольник 
На этот раз Вася решил создать онлайн-калькулятор геометрических фигур. Помог ему создать калькулятор треугольников, который сможет проверять существование треугольника, считать площадь и периметр.

### Процесс реализации
1. Написал класс `Triangle`.
    * Конструктор класса принимает три стороны треугольника.
    * В случае нарушения правила существования треугольника (сумма двух сторон меньше третьей) выбрасывается исключение с ошибкой *«Треугольник с такими сторонами не существует»*.
    * Геттер `perimeter` возвращает периметр треугольника.
    * Геттер `area` возвращает площадь треугольника. Для подсчёта площади использовал [формулу Герона](https://ru.wikipedia.org/wiki/%D0%A4%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D0%B0_%D0%93%D0%B5%D1%80%D0%BE%D0%BD%D0%B0). 
2. Написал функцию `getTriangle`.
    * Аргументами функции были три значения длин сторон.
    * Вернул новый объект треугольника.
    * В случае перехвата исключения вернул объект с двумя геттерами `area` и `perimeter`, которые вернули строку: *«Ошибка! Треугольник не существует»*.


## Результат решения и проверка через [тесты](https://maximbestintheworld.github.io/bjs-2-homeworks/6.exception-closure/)
